### ISSUE TITLE
Nuevos campos en el formulario de administración

### ISSUE THREAD

**Issue by KefDS** [jobcespedes/moodle-mod_bigbluebuttonbn#1]
Agregar nuevos campos en el formulario de administración del plugin
Añadir en formulario de administración:
- [x] Región (Servicio de orquestación)
- [x] Parámetros en la plantilla (por ahora key)

**Comment by KefDS** [comment]
Añadir en formulario de administración:
[ ] Región (Servicio de orquestación)
[ ] Parámetros en la plantilla (por ahora key)

**Comment by carlosmataguzman** [comment]
Hace falta proveer un campo para el URL con la plantilla del stack?

**Comment by ghost** [comment]
Los parámetros los pedí en formato JSON. Podemos usar esto para convertirlos en array asociativo: http://php.net/manual/es/function.json-decode.php
