### ISSUE TITLE
Tarea agendada no presente al instalar primera vez

### ISSUE THREAD

**Issue by jobcespedes** [jobcespedes/moodle-mod_bigbluebuttonbn#14]
Al instalar el modulo BBB en Moodle (branch develop, commit 4eb321f4bb1ea493c5), no se encontró la tarea agendada respectica en Moodle

**Comment by ghost** [comment]
Tenemos que revisar esto en el próximo deploy ya que la tarea sí viene dentro del código en [db/tasks.php](https://github.com/jobcespedes/moodle-mod_bigbluebuttonbn/blob/4eb321f4bb1ea493c5f375b30b25c8532af9b595/db/tasks.php)

**Comment by ghost** [comment]
Se realzió una instalación y la tarea agendada sí está presente.
