### ISSUE TITLE
Validación interfaz de administración | modo estático

### ISSUE THREAD

**Issue by jobcespedes** [jobcespedes/moodle-mod_bigbluebuttonbn#15]
La validación en la interfaz de administración de BBB se realiza en elementos del modo dínamico aún cuando este modo no está activado. Esto significa que al instalar desde cero hay que ingresar datos de conexión a Openstack aun cuando estos datos no se tiene y va a funcionar en modo estático

**Comment by ghost** [comment]
Intentar hacer validación para los dos casos. Hacer una validación dinámica al construir settings.php donde se devuelva una expresión regular si el campo de integración con OpenStack está activado.

**Comment by ghost** [comment]
Se resuelve en commit 4b58059dd059f47687ca4fed3531532f645d8a17 Ahora las opciones aparecen solo cuando se está usando la integración con OpenStack.
