### ISSUE TITLE
Hora 

### ISSUE THREAD

**Issue by jobcespedes** [jobcespedes/moodle-mod_bigbluebuttonbn#16]
"Cierre de ingreso" puede ser igual que "Apertura de ingreso". Debería validar que "Cierre de ingreso" sea una hora mayor que "Apertura de ingreso".

**Comment by jobcespedes** [comment]
Como mejora: "Cierre de ingreso"  debe tener una propuesta inicial que sirva en la mayoría de los casos. Por ejemplo 15 minutos despues "Apertura de ingreso"

**Comment by ghost** [comment]
Se resolvió en commit fdb9fbc139f284d15e12d837b594556b953d647a
