### ISSUE TITLE
Boton de unirse a VC sigue presente luego de destruída la VM

### ISSUE THREAD

**Issue by jobcespedes** [jobcespedes/moodle-mod_bigbluebuttonbn#17]
El botón de "Ingresar a sesión" sigue presente luego de destruída la VM. Lo anterior cuando se configura la fecha "Accesso cerrado" más allá de la duración. Por ejemplo

Acceso abierto: 12:00
Accesso cerrado: 14:00
Duración: 60

En la reserva anterior, un usuario que ingresa entre las 13:00 y 14:00 puede ver el botón "Ingresar a sesión"

**Comment by ghost** [comment]
Corregir el bug y hacer un issue paraj la mejora. (Usa  JS para rellenar las horas disponibles de reserva.)

**Comment by ghost** [comment]
Se arregla en commit 7f5c291558033caea11f45d05b150a6d6a81bc76
