### ISSUE TITLE
Intenta eliminar stack/vm no existente en OpenStack en cada ejecución de la tarea

### ISSUE THREAD

**Issue by jobcespedes** [jobcespedes/moodle-mod_bigbluebuttonbn#19]
La tarea agendada sigue intentando eliminar una MV que no existe en OpenStack cada vez que corre. Lo anterior produce un mensaje de error por cada ejecución, similar a:

> 09/08/2017 03:44:07 am The bbb host cannot be destroy. Try delete it manually. Meeting id: a806365e85a7029ffd3e26321c22e7432788827c

**Comment by ghost** [comment]
Se arregla en commit 795ef068a39f412025b8dcfdb1810aeaff9b3063. Esto se piensa mejorar en la 3ra entrega para que use el campo 'deletiontime' como base para saber si debe seguir intentando o no la eliminación.
