### ISSUE TITLE
'creationtime' y 'deletiontime' no son establecidos correctamente

### ISSUE THREAD

**Issue by jobcespedes** [jobcespedes/moodle-mod_bigbluebuttonbn#20]
'creationtime' siempre es establecido en 0
'deletiontime' siempre es establecido en null

**Comment by ghost** [comment]
Revisar si se va a utilizar en en la resilencia o no. Si no se usa eliminar los campos de la base de datos.

**Comment by ghost** [comment]
Se mantienen los campos para la próxima versión. Se recomienda mantener los campos, así mismo se corrige  un *typo* en el campo `creationtime`  corregir en la base de datos de producción editando el nombre del campo.  El cambio del typo viene en 6579c836b369115d7dcd02565d8fb8516c2a3b70
