### ISSUE TITLE
Las VMs al finalizar la duración a pesar de "bigbluebuttonbn_conference_extra_time"

### ISSUE THREAD

**Issue by jobcespedes** [jobcespedes/moodle-mod_bigbluebuttonbn#21]
Las VM se eliminan al alcanzar la duración a pesar de tener "bigbluebuttonbn_conference_extra_time" en 30 minutos

**Comment by ghost** [comment]
La funcionalidad del tiempo extra se implementó en el módulo de reservaciones (2da entrega) pero originalmente se había planteado como una mejora (3ra entrega). Se mantiene para la próxima versión del plugin, es decir para la 3ra entrega.

**Comment by ghost** [comment]
Se cierra el issue debido a que va para la 3ra entrega.
