### ISSUE TITLE
Las VMs se se crean hasta una hora antes de su hora de inicio

### ISSUE THREAD

**Issue by jobcespedes** [jobcespedes/moodle-mod_bigbluebuttonbn#22]
Las VMs se están creando mucho antes de su hora de inicio.

**Comment by ghost** [comment]
Esto es normal ya que la creación se intenta una hora antes para poder aplicar resilencia en un futuro. Se puede cambiar el valor por defecto. Este  se define en la linea 22 de `classes/openstack/moodle_bbb_openstack_stacks_management_tasks.php`

Definición:
`
   const UPCOMING_MEETINGS_MINUTES = 60;
`
