### ISSUE TITLE
Valor confuso en campo "Cierre de ingreso"  al editar reserva

### ISSUE THREAD

**Issue by jobcespedes** [jobcespedes/moodle-mod_bigbluebuttonbn#24]
Al editar una reserva con fecha establecida, el valor para el campo "Cierre de ingreso(en minutos)" se recalcula desde la fecha preestablecida. Se podría mejorar, si el valor existe en la base de datos, dejarlo. Si no, entonces proponer un valor. De lo contrario, al modificar se corre el riesgo de dar un valor que no tiene sentido.

**Comment by ghost** [comment]
Con la nueva interfaz esto ya no sucede.  Hay validaciones para asegurar que el valor que existe siempre tenga sentido.  El valor de "Cierre de ingreso(en minutos)" puede ser cualquiera excepto: 

* Valores negativos
* Valores que sea mayor al tiempo de duración de la conferencia
* Valores menores al tiempo de inicio de la videoconfrencia
* Valores iguales al tiempo de inicio de la videoconferencia
