### ISSUE TITLE
Error sobre OpenStack estando deshabilitado modo "Servidores BBB en demanda"

### ISSUE THREAD

**Issue by jobcespedes** [jobcespedes/moodle-mod_bigbluebuttonbn#25]
Aún estando deshabilitado modo "Servidores BBB en demanda" y los campos vacíos se genera un error el el archivo "log/openstack_errors" en cada ejecución del cron de BBB en moodle:

[2017-10-19 08:50:02] Error: Check your network, openstack service or configuration in moodle. The upcoming meetings will be canceled.
Unrecognized credential secret

**Comment by ghost** [comment]
Resuelto en release/ucr-bbb-v.2.0.8
