### ISSUE TITLE
Añadir campos necesarios en la base de datos para que funcione con OpenStack

### ISSUE THREAD

**Issue by KefDS** [jobcespedes/moodle-mod_bigbluebuttonbn#5]
Se necesita:
- [x] IP
- [x] Key
- [x] Nombre del stack

**Comment by KefDS** [comment]
- [x] ~~host_state~~
  *se cambia el nombre para mantener consistencia con otros campos de la tabla
- [x] bbb_server_status

**Comment by ghost** [comment]
Se agrega campo para almacenar la duración de la conferencia y saber cuando es necesario destruir la máquina virtual.
- [x] bbb_meeting_duration
